# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('nonvariableParent', models.CharField(max_length=20)),
                ('hpG', models.CharField(max_length=10)),
                ('strG', models.CharField(max_length=10)),
                ('magG', models.CharField(max_length=10)),
                ('skillG', models.CharField(max_length=10)),
                ('spdG', models.CharField(max_length=10)),
                ('lckG', models.CharField(max_length=10)),
                ('defG', models.CharField(max_length=10)),
                ('resG', models.CharField(max_length=10)),
                ('classP', models.CharField(max_length=30)),
                ('class2', models.CharField(max_length=30)),
            ],
        ),
    ]
